
import { Geist, Geist_Mono, Style_Script } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Features from "./components/Features";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";
import Cart from "./components/Cart";

const styleScript = Style_Script({
  subsets: ['latin'],
  weight: '400', // Style Script only has 400
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${styleScript.variable} antialiased text-[#212121] bg-[#ECE9E2] `}>
        <CartProvider>
          <Header />
          <Cart/>
          {children}
          <Features />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
